services:
    frontend:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace
        ports:
            - "5173:5173"
        command: /bin/sh -c "while sleep 1000; do :; done"
        environment:
            - windir # Defined on Windows but not on other platforms
