import React from "react";
import Header from "~/components/header";
import PlanCard from "~/components/planCard";
import ReportCard from "~/components/reportsCard";

import planPdf from "app/assets/CCC-Strategic-Plan-2024-27-1.pdf";
import report1 from "app/assets/Town-Gown-Full-Report_final.Report.1.pdf";
import report2 from "app/assets/Community-level-consequences-of-high-risk-drinking_final.Report.2.pdf";
import report3 from "app/assets/CCC-UNC-SWCCC-CoD-Final-Report.Report.3.pdf";
import report4 from "app/assets/CCC-The-Burden-of-Excessive-Drinking-in-Orange-County-NC-Final-Report.Report.4.pdf";

export default function Research() {
    const openPDF = (url: string) => {
        window.open(url, "_blank");
    };

    return (
        <main>
            <Header />
            <div className="max-w-6xl mx-auto px-4 py-10">
                <h1 className="text-3xl text-center font-bold mb-8">
                    Research Page
                </h1>

                <div className="text-center text-gray-700 mb-8 max-w-4xl mx-auto">
                    <p className="mb-2">
                        Check out some research and resources generated by the
                        CCC. These resources are available freely for
                        non-commercial use; if you do use one of our resources,
                        we'd love to know about it. Let us know by e-mailing{" "}
                        <a
                            href="mailto:ccc@downtownchapelhill.com"
                            className="text-blue-400 hover:text-blue-600 font-medium"
                        >
                            ccc@downtownchapelhill.com
                        </a>
                        .
                    </p>
                </div>

                <PlanCard
                    title="Strategic Plan"
                    summary="Using a facilitated process, key partners determined the next strategies of the CCC based on available data and trends, what works locally, and what is within the capacity of the CCC. Adopted strategies prioritize the ability to influence the environment and promote population-level health while applying a harm reduction lens. Strategies are derived largely from the alcohol-related evidence base, with the intention that strategies may be modified and applied to other substance use behaviors as those issues arise and as that evidence base evolves."
                    buttonText="View Plan"
                    onClick={() => {
                        openPDF(planPdf);
                    }}
                />

                <section className="mt-8">
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                        <ReportCard
                            title="Findings & Recommendations of the Town/Gown Collaborative"
                            summary="Using lessons learned from the SPARC Study (Wake Forest University), the latest available research, and a comprehensive community engagement process, these findings and recommendations created the foundations of the Chapel Hill Campus & Community Coalition in 2014."
                            buttonText="View Report"
                            onClick={() => {
                                openPDF(report1);
                            }}
                        />
                        <ReportCard
                            title="Community-Related Consequences of High-Risk Drinking: Chapel Hill, NC"
                            summary="Residents of Chapel Hill’s historic Northside and Cameron-McCauley neighborhoods report negative impacts from UNC-CH student drinking, including vandalism and noise, with Northside residents highlighting racial disparities in how disruptive behavior is addressed compared to generally positive perceptions in Cameron-McCauley."
                            buttonText="View Report"
                            onClick={() => {
                                openPDF(report2);
                            }}
                        />
                        <ReportCard
                            title="UNC-CH Color of Drinking Project"
                            summary="The Color of Drinking survey at UNC-Chapel Hill revealed that students, particularly LGBTQ+ individuals and students of color, face disproportionate mental health and safety harms from the campus alcohol culture despite drinking less than their white, non-LGBTQ+ peers."
                            buttonText="View Report"
                            onClick={() => {
                                openPDF(report3);
                            }}
                        />
                        <ReportCard
                            title="The Burden of Excessive Drinking in Orange County, NC"
                            summary="Excessive drinking in Orange County, NC, cost $111.8 million in 2017 due to healthcare expenses, productivity losses, and alcohol-related emergencies, contributing to 15.9% of deaths, with significant impacts on younger populations from violence-related fatalities."
                            buttonText="View Report"
                            onClick={() => {
                                openPDF(report4);
                            }}
                        />
                    </div>
                </section>
            </div>
        </main>
    );
}
